src/Northwind.Web/Controllers/CategoriesController.cs
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Northwind.Application.Interfaces;
using Northwind.Web.Utilities.Filters;
using Northwind.Web.ViewModels.Categories;
using System.IO;
using System.Threading.Tasks;

namespace Northwind.Web.Controllers
{
    [LogAction(true)]
    [ApiExplorerSettings(IgnoreApi = true)]
    [Authorize]
    public class CategoriesController : Controller
    {
        private readonly ICategoryService _categoryService;
        private readonly IMapper _mapper;

        public CategoriesController(ICategoryService categoryService, IMapper mapper)
        {
            _categoryService = categoryService;
            _mapper = mapper;
        }
        public async Task<IActionResult> Index()
            => View(await _categoryService.GetAllAsync());

        [Route("images/{id}")]
        [Route("[controller]/[action]/{id}")]
        public async Task<IActionResult> GetImage(int id)
            => File(await _categoryService.GetPictureByIdAsync(id), "image/bmp");

        [HttpGet]
        public async Task<IActionResult> EditImage(int id)
            => View(_mapper.Map<EditImageViewModel>(await _categoryService.GetByIdAsync(id)));


        [HttpPost]
        public async Task<IActionResult> EditImage(EditImageViewModel model, IFormFile uploadedFile)
        {
            if (ModelState.IsValid)
            {
                await using var memoryStream = new MemoryStream();
                await uploadedFile.CopyToAsync(memoryStream);
                model.Picture = memoryStream.ToArray();

                await _categoryService.EditImageById(model.CategoryID, model.Picture);
            }

            return RedirectToAction("Index");
        }
    }
}

src/Northwind.Web/Controllers/CategoryController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Northwind.Core.Interfaces;
using Northwind.Core.Models;
using Northwind.Web.Filters;
using System.IO;
using System.Threading.Tasks;

namespace Northwind.Web.Controllers
{
    [LogAction(true)]
    public class CategoryController : Controller
    {
        private readonly IRepository<CategoryDTO> _db;
        public CategoryController(IRepository<CategoryDTO> db)
        {
            _db = db;
        }
        public async Task<IActionResult> Index()
        {
            var categories = await _db.FindAllAync();
            return View(categories);
        }

        [Route("images/{id}")]
        [Route("[controller]/[action]/{id}")]
        public async Task<IActionResult> GetImage(int? id)
        {
            var category = await _db.FindAync(id);

            if (category == null)
            {
                return NotFound();
            }

            var image = category.Picture;
            return File(image, "image/bmp");
        }

        [HttpGet]
        public async Task<IActionResult> EditImage(int? id)
        {
            var category = await _db.FindAync(id);

            if (category == null)
            {
                return NotFound();
            }

            return View(category);
        }

        [HttpPost]
        public async Task<IActionResult> EditImage(CategoryDTO category, IFormFile uploadedFile)
        {
            if (ModelState.IsValid)
            {
                await using var memoryStream = new MemoryStream();
                await uploadedFile.CopyToAsync(memoryStream);
                category.Picture = memoryStream.ToArray();

                _db.Update(category);
                await _db.SaveChangesAsync();
            }

            return RedirectToAction("Index");
        }
    }
}

src/Northwind.Web/Controllers/ProductController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Configuration;
using Northwind.Core.Interfaces;
using Northwind.Core.Models;
using Northwind.Web.Filters;
using System.Linq;
using System.Threading.Tasks;

namespace Northwind.Web.Controllers
{
    [LogAction(true)]
    public class ProductController : Controller
    {
        private readonly IRepository<ProductDTO> _db;
        private readonly IRepository<SupplierDTO> _dbSupplier;
        private readonly IRepository<CategoryDTO> _dbCategory;
        private readonly int _maximumAmountOfProducts;
        private readonly string _maximumAmountOfProductsKey = "MaximumAmountOfProducts";

        public ProductController(
            IRepository<ProductDTO> db,
            IRepository<SupplierDTO> dbSupplier,
            IRepository<CategoryDTO> dbCategory,
            IConfiguration configuration)
        {
            _db = db;
            _dbSupplier = dbSupplier;
            _dbCategory = dbCategory;
            _maximumAmountOfProducts =
                configuration.GetValue<int>(_maximumAmountOfProductsKey);
        }

        public async Task<IActionResult> Index()
        {
            var products = await _db.FindAllAync();

            if (_maximumAmountOfProducts == 0)
            {
                return View(products);
            }

            return View(products.Take(_maximumAmountOfProducts));
        }

        [HttpGet]
        public async Task<IActionResult> Create()
        {
            await PopulateProductsDropDownLists();
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(ProductDTO product)
        {
            if (ModelState.IsValid)
            {
                await _db.InsertAsync(product);
                await _db.SaveChangesAsync();

                return RedirectToAction("Index");
            }
            else
            {
                await PopulateProductsDropDownLists();
                return View(product);
            }
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id != null)
            {
                ProductDTO product = await _db.FindAync(id);
                if (product != null)
                {
                    await PopulateProductsDropDownLists();
                    return View(product);
                }
            }

            return NotFound();
        }

        [HttpPost]
        public async Task<IActionResult> Edit(ProductDTO product)
        {
            if (ModelState.IsValid)
            {
                _db.Update(product);
                await _db.SaveChangesAsync();

                return RedirectToAction("Index");
            }
            else
            {
                await PopulateProductsDropDownLists();
                return View(product);
            }
        }

        private async Task PopulateProductsDropDownLists()
        {
            ViewBag.Suppliers = new SelectList(await _dbSupplier.FindAllAync(), "SupplierID", "CompanyName");
            ViewBag.Categories = new SelectList(await _dbCategory.FindAllAync(), "CategoryID", "CategoryName");
        }
    }
}

src/Northwind.Web/Controllers/ProductsController.cs
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Configuration;
using Northwind.Application.Interfaces;
using Northwind.Domain.Entities;
using Northwind.Web.Utilities.Filters;
using Northwind.Web.ViewModels.Products;
using System;
using System.Threading.Tasks;

namespace Northwind.Web.Controllers
{
    [LogAction(true)]
    [ApiExplorerSettings(IgnoreApi = true)]
    [Authorize]
    public class ProductsController : Controller
    {
        private readonly IProductService _productService;
        private readonly IMapper _mapper;
        private readonly Lazy<int> _lazyMaxAmountOfProducts;
        protected int MaxAmountOfProducts => _lazyMaxAmountOfProducts.Value;

        public ProductsController(
            IProductService productService,
            IConfiguration configuration,
            IMapper mapper)
        {
            _productService = productService;
            _mapper = mapper;
            _lazyMaxAmountOfProducts = new Lazy<int>(
                configuration.GetValue<int>(nameof(MaxAmountOfProducts)));
        }

        public async Task<IActionResult> Index()
        {
            return View(await _productService.GetMaxAmountAsync(MaxAmountOfProducts));
        }

        [HttpGet]
        public async Task<IActionResult> Create()
        {
            await PopulateProductsDropDownLists();
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(CreateProductViewModel product)
        {
            if (ModelState.IsValid)
            {
                await _productService.CreateAsync(_mapper.Map<ProductEntity>(product));

                return RedirectToAction("Index");
            }
            else
            {
                await PopulateProductsDropDownLists();
                return View(product);
            }
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            await PopulateProductsDropDownLists();
            return View(_mapper.Map<EditProductViewModel>(await _productService.GetByIdAsync(id)));
        }

        [HttpPost]
        public async Task<IActionResult> Edit(EditProductViewModel product)
        {
            if (ModelState.IsValid)
            {
                await _productService.UpdateAsync(_mapper.Map<ProductEntity>(product));
                return RedirectToAction("Index");
            }
            else
            {
                await PopulateProductsDropDownLists();
                return View(product);
            }
        }

        private async Task PopulateProductsDropDownLists()
        {
            ViewBag.Suppliers = new SelectList(await _productService.GetSuppliers(), "SupplierID", "CompanyName");
            ViewBag.Categories = new SelectList(await _productService.GetCategories(), "CategoryID", "CategoryName");
        }
    }
}

src/Northwind.Web/Views/Shared/_FirstLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Northwind</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>@RenderSection("Header", false)</header>

    <div id="mySidebar" class="sidebar">
        <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">×</a>
        <a class="nav-link text-dark" asp-controller="Categories" asp-action="Index"><h5>Categories</h5></a>
        <a class="nav-link text-dark" asp-controller="Products" asp-action="Index"><h5>Products</h5></a>
        @if (User.IsInRole("admin"))
        {
            <a class="nav-link text-dark" asp-controller="Administrator" asp-action="Index"><h5>Users</h5></a>
        }
    </div>

    <div>
        <nav class="navbar">
            <button class="navbar-toggler navbar-dark" type="button" onclick="openNav()">
                <span class="navbar-toggler-icon"></span>
            </button>
            <vc:breadcrumb />
        </nav>
        <div style="padding-left: 40px; padding-top: 20px; padding-bottom: 20px">
            <main role="main">
                @RenderBody()
            </main>
        </div>
    </div>

    <footer class="border-top footer text-muted">
        @if (IsSectionDefined("Footer"))
        {
            @RenderSection("Footer")
        }
        else
        {
            <div class="container">
                &copy; 2021 - Northwind
            </div>
        }
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

src/Northwind.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Northwind</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <div id="mySidebar" class="sidebar">
        <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">×</a>
        <a class="nav-link text-dark" asp-controller="Category" asp-action="Index"><h5>Categories</h5></a>
        <a class="nav-link text-dark" asp-controller="Product" asp-action="Index"><h5>Products</h5></a>
    </div>

    <div id="sidebarInvoker">
        <nav class="navbar navbar-light bg-light" onclick="openNav()">
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarContent" aria-controls="navbarContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <a class="navbar-brand mr-auto p-3" asp-controller="Home" asp-action="Index">Home</a>
        </nav>
        <div class="container">
            <main role="main" class="pb-3">
                @RenderBody()
            </main>
        </div>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Northwind
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

src/Northwind.Web/Views/Shared/_SecondLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Northwind</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <div id="mySidebar" class="sidebar">
        <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">×</a>
        <a class="nav-link text-dark" asp-controller="Categories" asp-action="Index"><h5>Categories</h5></a>
        <a class="nav-link text-dark" asp-controller="Products" asp-action="Index"><h5>Products</h5></a>
        @if (User.IsInRole("admin"))
        {
            <a class="nav-link text-dark" asp-controller="Administrator" asp-action="Index"><h5>Users</h5></a>
        }
    </div>

    <div>
        <nav class="navbar">
            <button class="navbar-toggler navbar-dark" type="button" onclick="openNav()">
                <span class="navbar-toggler-icon"></span>
            </button>
            @if (User.Identity.IsAuthenticated)
            {
                <form method="post" asp-controller="Account" asp-action="Logout">
                    <input type="submit" class="btn btn-lg" style="color: white" value="Logout" />
                </form>
            }
            else
            {
                <div class="container-fluid fixed-top justify-content-end">
                    <a class="btn btn-lg" style="color: white; padding-top: 18px" asp-controller="Account" asp-action="Login">Login</a>
                    <a class="btn btn-lg" style="color: white; padding-top: 18px" asp-controller="Account" asp-action="Register">Register</a>
                </div>
            }
        </nav>
        <div style="padding-left: 40px; padding-top: 20px; padding-bottom: 20px">
            <main role="main">
                @RenderBody()
            </main>
        </div>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Northwind
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>